# Pipeline to execute sample Java app that is
# triggered by the VehiclesCatalogApi.

trigger: 
  branches:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- powershell: Start-Sleep -Seconds 60
  displayName: Delay One Minute
  name: DelayStep
  env:
    name: Microsoft

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
